### ISSUE TITLE
rest_api: rename `json_response` paginator to `json_link`

### ISSUE THREAD

**Issue by burnash** [dlt-hub/verified-sources#513]
### Description

Currently, in the rest_api there are two paginators which use URL of the next page to paginate the results: `json_response` and `header_link`. `json_response` uses the `next` key in the JSON response, while `header_link` uses the `Link` header of the response.

### Proposal

To be more consistent with the naming, and better reflect the actual functionality, we should rename the `json_response` paginator to `json_link`.

### Task
- [x] Rename the `json_response` paginator to `json_link` in the rest_api module.
- [x] Update the doc in the dlt core repo
- [x] Update tests if needed

### Related issues

https://github.com/dlt-hub/dlt/issues/1495
