### ISSUE TITLE
rest_api: incremental config: rename `transform` to `convert`

### ISSUE THREAD

**Issue by burnash** [dlt-hub/verified-sources#544]
### Background

https://github.com/dlt-hub/verified-sources/issues/507 introduced a way to specify a function to convert incremental field values.

### Proposal

Rename the configuration key from `transform` to `convert` to better indicate the purpose of this setting.

### Task

- [x] Rename the setting
- [x] Add a deprecation message
- [x] Update the docs PR with a new name
